Bonding address
Itheum/data-dex pull request #1315
Opened 2024-04-11 12:27 UTC by Enciusan

### Description

Check all boxes that apply and review your code if you can't tick them all yet:

- [ ] Did you test your changes in logged out, mainnet logged in and devnet logged in modes?
- [ ] Did you test your changes in mobile, tablet and desktop modes?
- [ ] Did you test your changes with or without the Itheum Web2 API availability? (don't forget about "graceful fallback")
- [ ] Did you use good user alerts and error messages? (and put them in language.ts)
- [ ] Did you leave the code base cleaner than you found it overall (done reasonable refactoring efforts wherever you felt that was needed)?

2024-04-12 10:32 UTC, michavie commented
@Enciusan we have released a Deep Link Builder yesterday to make it easy to generate deep links: 

NPM: https://www.npmjs.com/package/@peerme/sdk

Usage:

![Screenshot 2024-04-12 at 12 32 21 PM](https://github.com/Itheum/data-dex/assets/39144548/a9458121-257a-4f8a-b9c4-2a086f44f460)

2024-04-12 11:37 UTC, Enciusan commented
Hello @michavie i found out this error pops up when i try to use it :) 
![image](https://github.com/Itheum/data-dex/assets/92076681/78a4fde2-772c-4e37-addc-cd49917f93d0)

2024-04-12 11:44 UTC, michavie commented
@Enciusan Importing like this does not work?

```
import { ProposalDeepLinkBuilder } from '@peerme/sdk'
```

We may need to add a default export to use it similar to this:

```
import PeerMe from '@peerme/sdk'
PeerMe.ProposalDeepLinkBuilder
```

2024-04-22 13:30 UTC, damienen requested changes

2024-04-22 13:30 UTC, damienen commented on package.json
> +    "@peerme/sdk": "^0.2.1",
This should have a stable version

2024-04-22 13:30 UTC, damienen commented on src/pages/Bonding/Bonding.tsx
> +    const splittedAddresses = bondContractAdminDevnet.split(", ");
Here it should be a bit less restrictive.

Just split by "," and then use trim() to get rid of white spaces

2024-04-22 13:30 UTC, damienen commented on src/pages/Bonding/Bonding.tsx
> +  // console.log()
Delete this comment

2024-04-22 13:30 UTC, damienen commented on src/pages/Bonding/Bonding.tsx
> +    console.log(adminAddress.includes(address), address, adminAddress, address === adminAddress);
Deleete this log

2024-04-22 13:30 UTC, damienen commented on src/pages/Bonding/components/BondingParameters.tsx
> +    // console.log(url);
Delete comment

2024-04-22 13:30 UTC, damienen commented on src/pages/Bonding/components/BondingParameters.tsx
> +  // const earlyWithdrawalDeeplinkUrl = (newEarlyWithdrawalValue: number) => {
Delete comments

2024-04-23 11:49 UTC, damienen approved these changes

2024-04-23 11:50 UTC, damienen approved these changes

2024-04-23 11:52 UTC, merged